"""Constants for the Wallbox integration."""

from .obis import *

DOMAIN = "ha-eCB1"
UPDATE_INTERVAL = 10

#CONF_MAX_AVAILABLE_POWER_KEY = "max_available_power"
#CONF_MAX_CHARGING_CURRENT_KEY = "max_charging_current"
CONF_ACT_CHARGING_CURRENT_KEY = "currentpwmamp"
CONF_ADDED_ENERGY_KEY = "added_energy"
CONF_ADDED_RANGE_KEY = "added_range"
CONF_AI_MODE_KEY = "autostartstop"
CONF_BASEURL = "url"
CONF_CHARGING_MODES_KEY = "charging_modes"
CONF_CHARGING_POWER_KEY = "charging_power"
CONF_CHARGING_SPEED_KEY = "charging_speed"
CONF_CHARGING_TIME_KEY = "charging_time"
CONF_CONNECTED_KEY = "connected"
CONF_CONNECTIONS = "connections"
CONF_COST_KEY = "cost"

CONF_CURRENT_MODE_KEY = "mode"
CONF_CURRENT_VERSION_KEY = "currentVersion"
CONF_DATA_KEY = "chargecontrol"
CONF_DEPOT_PRICE_KEY = "depot_price"
# CONF_KWH_OUT_KEY = "1-0:1.8.0"
# CONF_KWH_IN_KEY = "1-0:2.8.0"
CONF_LOCKED_UNLOCKED_KEY = "stateid"
CONF_MAX_AVAILABLE_POWER_KEY = "supplylinemaxamp"
CONF_MAN_CHARGING_CURRENT_KEY = "manualmodeamp"
CONF_METERS_KEY = "meter"
CONF_NAME_KEY = "name"
#CONF_PART_NUMBER_KEY = "part_number"
CONF_PART_NUMBER_KEY = "type"
CONF_SERIAL_NUMBER_KEY = "serial"
#CONF_SOFTWARE_KEY = "software"
CONF_SOFTWARE_KEY = "os_version"
CONF_STATE_OF_CHARGE_KEY = "state_of_charge"
CONF_STATION = "station"
CONF_STATUS_DESCRIPTION_KEY = "status_description"
CONF_STATUS_ID_KEY = "status_id"
CONF_SYS_INFO_KEY = "system"
